version: "3.7"

services:
  node-red:
    image: nodered/node-red:3.0
    environment:
      TZ: "Europe/Berlin"
    networks:
      - node-red-sentry-node
    ports:
      - "1880:1880"
    volumes:
      - node-red:/data
      - ./:/repo

volumes:
  node-red:

networks:
  node-red-sentry-node: